export const allReports = [
  {
    "S/NO": 1,
    "Project Name": "Routine maintenance of solar PV systems for Napeikar",
    "Sub-County": "Loima",
    Ward: "Turkwel",
    Location: "Napeikar",
    Department: "Energy",
    "Project cost": 1800000,
    Award: 1791000,
    Status: "New set of solar PV working. Old set not working",
    Northing: "3.005630N",
    Easting: "35.506110E",
    Remarks: "Old installation needs repairs/maintenace works",
  },
  {
    "S/NO": 2,
    "Project Name":
      "construction and completion of cess office, toilets and barrier at Loya",
    "Sub-County": "Loima",
    Ward: "Lokiriama/ Lorengippi",
    Location: "Loya",
    Department: "Revenue",
    "Project cost": 2600000,
    Award: 2357450,
    Status: "Works complete and structure in use",
    Northing: "2.513777N",
    Easting: "34.978482E",
    Remarks: "Cess office, Latrines and barrier complete. Ramp constructed",
  },
  {
    "S/NO": 3,
    "Project Name": "Completion of Lokiriama Revenue Centre",
    "Sub-County": "Loima",
    Ward: "Lokiriama/ Lorengippi",
    Location: "Lokiriama",
    Department: "Revenue",
    "Project cost": 40000000,
    Award: 37754017,
    Status: "Contractor not on site  Works not started",
    Northing: "2.5750372N",
    Easting: "34.870038E",
    Remarks: "No works started at all",
  },
  {
    "S/NO": 4,
    "Project Name": "Construction of staff houses, ward, fence and pit latrine",
    "Sub-County": "Loima",
    Ward: "Lokiriama/ Lorengippi",
    Location: "Lokiriama",
    Department: "Health",
    "Project cost": 10000000,
    Award: 9867750,
    Status:
      "Works not started at all                    Contractor not on site",
    Northing: "2.755548N",
    Easting: "34.879693E",
    Remarks: "No works started at all",
  },
  {
    "S/NO": 5,
    "Project Name": "Improvement of water facilities at lokiriama Water Supply",
    "Sub-County": "Loima",
    Ward: "Lokiriama/ Lorengippi",
    Location: "Lokiriama",
    Department: "Water",
    "Project cost": 7000000,
    Award: 6880900,
    Status: "No works done ",
    Northing: "2.754165N",
    Easting: "34.879693E",
    Remarks: "No works started at all",
  },
  {
    "S/NO": 6,
    "Project Name":
      "Drilling and Solarization of Namoruputh borehole and water improverment at Lokwatuba",
    "Sub-County": "Loima",
    Ward: "Loima",
    Location: "Namoruputh",
    Department: "Water",
    "Project cost": 4953000,
    Award: 4945660,
    Status: "Works complete Solarization andpiping of water done",
    Northing: "2.896280N",
    Easting: "34.954542E",
    Remarks: "Water improvement at Lokwatuba not done",
  },
  {
    "S/NO": 10,
    "Project Name": "Construction of fence at Lorugum VTC(Chain link)",
    "Sub-County": "Loima",
    Ward: "Turkwel",
    Location: "Lorugum",
    Department: "Vocational",
    "Project cost": 3000000,
    Award: 2962400,
    Status: "Construction of fence complete",
    Northing: "2.867854N",
    Easting: "35.264184E",
    Remarks: "Fence well constructed",
  },
  {
    "S/NO": 11,
    "Project Name": "Construction of Lodoket-engol ECDE",
    "Sub-County": "Loima",
    Ward: "Lobei/Kotaruk",
    Location: "Naipa",
    Department: "ECDE",
    "Project cost": 6500000,
    Award: 6549244,
    Status: "Building at lintel level",
    Northing: "2.520085N",
    Easting: "35.372060E",
    Remarks: "Structure incomplete At lintel level",
  },
  {
    "S/NO": 12,
    "Project Name": "Construction of Kakilala",
    "Sub-County": "Loima",
    Ward: "Lobei/Kotaruk",
    Location: "Kakilala",
    Department: "ECDE",
    "Project cost": 6500000,
    Award: 6024994,
    Status: "Construction at foundation level",
    Northing: "2.851183N",
    Easting: "35.363920E",
    Remarks:
      "Construction materials on site. Two buildings both at foundation level",
  },
  {
    "S/NO": 13,
    "Project Name": "Construction of maternity ward at Turkwel Health Centre",
    "Sub-County": "Loima",
    Ward: "Turkwel",
    Location: "Turkwel",
    Department: "Health",
    "Project cost": 9000000,
    Award: 8707499,
    Status: "Building at lintel level",
    Northing: "2.913868N",
    Easting: "35.404001E",
    Remarks: "Good progress in terms of construction works. Materials on site",
  },

  {
    "S/NO": 15,
    "Project Name":
      "Lochor-ekuyen dispensary, latrines, staff quarters and fencing",
    "Sub-County": "Loima",
    Ward: "Loima",
    Location: "Lochor-ekuyen",
    Department: "Health",
    "Project cost": "",
    Award: "",
    Status: "Construction works at 90%. Only windows and paint missing",
    Northing: "2.866348N",
    Easting: "35.183150E",
    Remarks:
      "construction works almost complete. Dispensary lacking windows and paint",
  },
  {
    "S/NO": 16,
    "Project Name": "Peace resettlement camp",
    "Sub-County": "T/North",
    Ward: "Lakezone",
    Location: "Todonyang",
    Department: "Peace",
    "Project cost": 10000000,
    Award: 9846216,
    Status: "Not started ",
    Northing: "4.441895N",
    Easting: "35.925478E",
    Remarks: "No works done ",
  },
  {
    "S/NO": 17,
    "Project Name":
      "Renovation of cess points including construction of toilet & barrier at Kataboi",
    "Sub-County": "T/North",
    Ward: "Lakezone",
    Location: "Kataboi",
    Department: "Revenue",
    "Project cost": 800000,
    Award: 798000,
    Status: "Complete ",
    Northing: "3.7538942N",
    Easting: "35.830250E",
    Remarks: "Cess ,toilet and barrier done ",
  },
  {
    "S/NO": 18,
    "Project Name":
      "Renovation of cess points including construction of toilet & barrier at Nakalale",
    "Sub-County": "T/North",
    Ward: "Nakalale",
    Location: "Nakalale",
    Department: "Revenue",
    "Project cost": 800000,
    Award: 778200,
    Status: "Complete",
    Northing: "3.510842N",
    Easting: "35.226217E",
    Remarks: "Work done",
  },
  {
    "S/NO": 20,
    "Project Name": "Rehalibitation of Dupa Pump (Catholic Mission)",
    "Sub-County": "T/North",
    Ward: "Kaeris",
    Location: "Kaeris",
    Department: "Water",
    "Project cost": 4000000,
    Award: 4000000,
    Status: "Not started ",
    Northing: "3.980647N",
    Easting: "35.485637E",
    Remarks: "No work done ",
  },

  {
    "S/NO": 22,
    "Project Name": "Improvement of  Todonyang Water Supply",
    "Sub-County": "T/North",
    Ward: "Lakezone",
    Location: "Todonyang",
    Department: "Water",
    "Project cost": 5000000,
    Award: 4970220,
    Status: "Not started ",
    Northing: "4.441895N",
    Easting: "35.925478E",
    Remarks: "No works done ",
  },
];
